languageCode: "en-us"
baseUrl: "https://integratn.io"
title: "INTEGRATN.io"
theme: "CodeIT"
paginate: 10
# comment for preview deploy
# disqusShortname: "yourdiscussshortname"
googleAnalytics: G-MSXV04G0ZQ
enableRobotsTXT: true
enableEmoji: true

menu:
  main:
  - identifier: blog
    name: Blog
    title: Blog
    url: /posts/
    weight: 1
  - identifier: categories
    name: Categories
    title: Categories
    url: /categories/
    weight: 2
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 3
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 100
 
taxonomies:
  category: categories
  tag: tags
  series: series

author:
  name: James
  link: "https://twitter.com/james_dreier"

params:
  analytics: 
    enable: true
  version: "0.2.X"
  author: "James Dreier"
  email: "james@integratn.io" # used for microformats
  avatar: "images/me2.png" # used for microformats
  images: 
  - "images/INTEGRATN-logo.png"
  description: "A lot of Devops | with just a little bit of crazy"
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: false
  disableSummary: false
  adsense:
    client: ca-pub-3643357265443233
    inArticleSlot: "8178703612"
  # customCSS:
  #   - assets/css/my.css
  # utteranc.es support
  # utterancesRepo: ""  # mandatory
  # utterancesTheme: "" # optional
  # utterancesIssue: "" # optional
  # utterancesLabel: "" # optional
  webmentions:
    # url: https://integratn.io/webemntions/receive
    login: integratn.io
    pingback: true
  social:
    github: "jamesattensure"
    linkedin: "jjdreier"
    twitter: "james_dreier"
    devto: "jamesatintegratnio"
    rss: true
  home:
    rss: 10
    profile:
      enable: true
      avatarURL: "/images/me2.png"
      social: true
      subtitle: "A lot of Devops | with just a little bit of crazy"
      typeit: true
    posts:
      enable: true
  footer:
    copyright: true
    author: true
    since: 2021
    license: '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  page:
    library:
      css:
        myCSS: "css/my.css"
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: True
      Whatsapp: false
      Pinterest: false
      Tumblr: false
      HackerNews: true
      Reddit: true
      VK: false
      Buffer: false
      Xing: false
      Line: true
      Instapaper: false
      Pocket: true
      Digg: false
      Stumbleupon: false
      Flipboard: false
      Weibo: true
      Renren: false
      Myspace: false
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
      Telegram: false
markup:
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true