languageCode: "en-us"
baseUrl: ""
title: "INTEGRATN.io"
theme: "anubis"
paginate: 10
disqusShortname: "yourdiscussshortname"
googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 100
  - identifier: about
    name: About
    title: About
    url: /about/
    wieight: 1

taxonomies:
  category: categories
  tag: tags

params:
  author: "James Dreier"
  email: boboysdadda@gmail.com # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: "A lot of Devops | with just a little bit of crazy"
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: false
  disableSummary: false
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
  - id: github
    name: jamesattensure
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown