languageCode: "en-us"
baseUrl: "https://integratn.io"
title: "INTEGRATN.io"
theme: "anubis"
paginate: 10
# disqusShortname: "yourdiscussshortname"
googleAnalytics: G-MSXV04G0ZQ
enableRobotsTXT: true

menu:
  main:
  - identifier: blog
    name: Blog
    title: Blog
    url: /posts/
    weight: 1
  - identifier: categories
    name: Categories
    title: Categories
    url: /categories/
    weight: 2
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 3
  - identifier: series
    name: Series
    title: Series
    url: /series/
    weight: 4
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 100
 
taxonomies:
  category: categories
  tag: tags
  series: series

params:
  author: "James Dreier"
  email: james@integratn.io # used for microformats
  avatar: "images/me.png" # used for microformats
  images: 
  - "images/INTEGRATN-logo.png"
  description: "A lot of Devops | with just a little bit of crazy"
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: false
  disableSummary: false
  adsense:
    client: ca-pub-3643357265443233
    inArticleSlot: "8178703612"
  # customCSS:
  #   - assets/css/my.css
  # utteranc.es support
  # utterancesRepo: ""  # mandatory
  # utterancesTheme: "" # optional
  # utterancesIssue: "" # optional
  # utterancesLabel: "" # optional
  # webmentions:
  #   url: https://yourdomain.com/webemntions/receive
  #   login: hugo-theme-anubis
  #   pingback: true
  social:
  - id: github
    name: jamesattensure
  - id: linkedin
    name: jjdreier
  - id: Twitter
    name: james_dreier

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown